SFDO-Community/OmbudsmanCloudCare

force-app/main/default/applications/Ombudsman_Cloud_Care.app-meta.xml
force-app/main/default/flexipages/OCC_Contact_Record_Page.flexipage-meta.xml
force-app/main/default/flexipages/OCC_Home_Page_Default.flexipage-meta.xml
force-app/main/default/objects/Case/listViews/All_OCC_Cases.listView-meta.xml
force-app/main/default/objects/Case/listViews/All_OCC_Open_Cases.listView-meta.xml
force-app/main/default/objects/Case/listViews/MyOCCOpenCases.listView-meta.xml
force-app/main/default/permissionsets/Ombundsman_Standard.permissionset-meta.xml
orgs/beta.json
orgs/feature.json
orgs/release.json

Readd Case List Views to repo with OCC name.
- Readd Case List Views
- Readd All Case List View to Home Page
- Update org json files for parity

Readd Case List Views

---

cumulusci.yml
unpackaged/config/qa/package.xml
unpackaged/config/qa/profiles/Admin.profile

Add admin profile config to qa flow

Add admin profile config to qa flow

---

force-app/main/default/flexipages/OCC_Home_Page_Default.flexipage-meta.xml
force-app/main/default/objects/EmailMessage/fields/Send_Case_to_Command_Message__c.field-meta.xml
force-app/main/default/quickActions/Case.Send_Case_to_Command.quickAction-meta.xml
force-app/main/default/workflows/Case.workflow-meta.xml
force-app/main/default/workflows/EmailMessage.workflow-meta.xml

Includes the workflow field update that makes Send Case to Command check the box.

Send Case to Command Working

---

datasets/sample.sql
force-app/main/default/flexipages/OCC_Home_Page_Default.flexipage-meta.xml

Accounts didn't have the Primary Contact. Two resource contacts didn't have primary affiliations. Also added a larger number of lines on the Open Cases list on the homepage.

Updates to Dataset/Homepage

---

cumulusci.yml
datasets/sample.sql

Found a typo in cumulusci.yml and fixed that. While I was at it, tiny changes to sample.sql to up some Time Spent field values.

MinorFixes

---

datasets/sample.sql

Uses relative dates for Tasks instead of fixed.

Relative Task Dates

---

force-app/main/default/layouts/Case-OCC Case Layout.layout-meta.xml

Remove email action from OCC case layout to allow for package creation.

Update Case-OCC Case Layout.layout-meta.xml

---

force-app/main/default/layouts/Contact-OCC Family Member.layout-meta.xml
force-app/main/default/layouts/Contact-OCC Resource Contact Layout.layout-meta.xml

Added Relationships related list to the two Contact page layouts.

Relationship lists to Contact Layouts

---

force-app/main/default/quickActions/Case.Send_Case_to_Command.quickAction-meta.xml

It was missing the HTML Body predefined field update.

Katie's Send Case to Command

---

cumulusci.yml
sfdx-project.json

Update cumulus.yml and sfdx-project.json files with ombudcare namespace.

Add ombudcare as namespace

---

orgs/demo.json
orgs/release.json

Update Demo to be Enterprise Edition.

Org Definition Files

---

force-app/main/default/reports/OmbudsmanCloudCare/New_Family_Members_Report_ccy.report-meta.xml
force-app/main/default/reports/OmbudsmanCloudCare/New_Family_Members_by_State_Report_ori.report-meta.xml

Reports titled "family member" did not have report filters to OCC Family Member record type.

Two Report FIlter Updates

---

force-app/main/default/dashboards/OCCDashboards.dashboardFolder-meta.xml
force-app/main/default/reports/OmbudsmanCloudCare.reportFolder-meta.xml

FolderShares

---

force-app/main/default/layouts/Contact-OCC Family Member.layout-meta.xml

Family Member Page Layout

---

force-app/main/default/quickActions/OCC_New_Case.quickAction-meta.xml

Adds an OCC-specific New Case global action.

New Case Global Action

---

force-app/main/default/quickActions/OCC_New_Case.quickAction-meta.xml

Fixes issue #79 
Adds layout and default value.

Fix new case action

---

force-app/main/default/objects/Contact/recordTypes/Family_Member.recordType-meta.xml
force-app/main/default/objects/Contact/recordTypes/Resource_Contact.recordType-meta.xml

Remove Lead Source from Picklist values

Remove Lead Source Picklist Values

---

unpackaged/config/customerorg/package.xml
unpackaged/config/customerorg/profiles/Admin.profile
unpackaged/config/customerorg/profiles/Ombudsman Standard User.profile
unpackaged/config/dev/profiles/Ombudsman Standard User.profile

Add Command Name to Admin and OCC Standard profiles for Dev Org and Customer Orgs so that field appears on install.
Add OCC Fields to OCC Standard Profile so that all packaged fields will appear in OCC Standard Profile.
#85

Add Command Name to FLS

---

force-app/main/default/applications/Ombudsman_Cloud_Care.app-meta.xml
force-app/main/default/applications/Ombudsman_Cloud_Care_Standard.app-meta.xml
force-app/main/default/flexipages/Ombudsman_Cloud_Care_UtilityBar1.flexipage-meta.xml
unpackaged/config/customerorg/profiles/Ombudsman Standard User.profile
unpackaged/config/dev/profiles/Ombudsman Standard User.profile

Create Standard App
Set as Default for OCC Profile
Remove visibility for Console App for OCC Profile
#94

Create Standard App

---

cumulusci.yml
unpackaged/config/dev/standardValueSets/CaseReason.standardValueSet
unpackaged/config/managed/standardValueSets/CaseReason.standardValueSet

Update Case Reason Picklist Value

---

cumulusci.yml
unpackaged/config/dev/standardValueSets/CaseReason.standardValueSet
unpackaged/config/managed/standardValueSets/CaseReason.standardValueSet

Keeping Up to Date with Master

---

cumulusci.yml
unpackaged/config/dev/standardValueSets/CaseReason.standardValueSet
unpackaged/config/managed/standardValueSets/CaseReason.standardValueSet

Keeping up to date on Master

---

cumulusci.yml
lib/admin_profile.xml
unpackaged/config/dev/profiles/Admin.profile
unpackaged/config/managed/profiles/Admin.profile

Update Unpackaged Admin profile to include custom case and task fields.

Update Unpackaged Admin profile

---

force-app/main/default/flexipages/OCC_Home_Page_Default.flexipage-meta.xml

Added OCC Community Help Desk with link as a rich text component to OCC Home page.

Homepage Help Component

---

force-app/main/default/reports/OmbudsmanCloudCare/Ombudsman_Registry_Activities_AzI.report-meta.xml

No changes that would affect functionality.
Added SAPR Incoming and SAPR Outgoing to Ombudsman Registry Activities report.

Fix Ombudsman Registry Activities Report

---

unpackaged/config/customerorg/profiles/Admin.profile
unpackaged/config/customerorg/profiles/Ombudsman Standard User.profile
unpackaged/config/dev/profiles/Admin.profile
unpackaged/config/dev/profiles/Ombudsman Standard User.profile
unpackaged/config/managed/profiles/Admin.profile

Make OCC Help and Training visible for Admin and OCC Profiles.
#131

Add Tab to Profiles

---

cumulusci.yml
unpackaged/config/customerorg/profiles/Admin.profile
unpackaged/config/customerorg/profiles/Ombudsman Standard User.profile
unpackaged/config/dev/package.xml
unpackaged/config/dev/profiles/Admin.profile
unpackaged/config/dev/profiles/Ombudsman Standard User.profile
unpackaged/config/dev/standardValueSets/CaseReason.standardValueSet
unpackaged/config/dev/standardValueSets/LeadStatus.standardValueSet
unpackaged/config/managed/standardValueSets/CaseReason.standardValueSet

Separate Unpacked and YML changes to allow for version 1.3 testing with Metecho.

Unpackaged YML Changes

---

cumulusci.yml
force-app/main/default/reports/OmbudsmanCloudCare/Ombudsman_Registry_Activities_AzI.report-meta.xml
unpackaged/config/customerorg/profiles/Ombudsman Standard User.profile
unpackaged/config/dev/profiles/Ombudsman Standard User.profile

Remove Red Cross Field from reports and profiles.

Remove Red Cross Field

---

.github/CODEOWNERS
.github/workflows/beta.yml
.github/workflows/feature.yml
.github/workflows/prod.yml

This PR migrates CI from MetaCI to GitHub Actions.

Add GitHub Actions workflows
